# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/crow')),
                ('bio', models.TextField(max_length=500)),
                ('github', models.TextField(max_length=500)),
                ('twitter', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=144)),
                ('image', models.ImageField(upload_to='uploads/projects')),
            ],
        ),
    ]
