# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
