# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20161229_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects'),
        ),
    ]
