# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_auto_20161229_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ada',
            name='bio',
        ),
        migrations.AlterField(
            model_name='ada',
            name='github',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ada',
            name='twitter',
            field=models.CharField(max_length=500),
        ),
    ]
