# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0005_auto_20161229_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ada',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static_pages/static/uploads/projects'),
        ),
    ]
