# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0006_auto_20170108_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/uploads/projects'),
        ),
    ]
